### ISSUE TITLE
Fast PBKDF2 algorithm

### ISSUE THREAD

**Issue by adinapoli** [haskell-crypto/cryptonite-openssl#4]
Hey @vincenthz ! I wanted to resume the conversation we started on Twitter, as it's gonna take a while with 140 chars at time 😁 . This is the state of affairs reassumed:

* I have developed the Haskell bindings to the [fastpbkdf2](https://github.com/ctz/fastpbkdf2) library, called, unsurprisingly [fastpbkdf2-hs](https://github.com/adinapoli/fastpbkdf2-hs)

* `fastpbkdf2` depends upon OpenSSL as it's using the SHA functions. Those functions uses some platform-optimised Assembly code, so the speed would be hard to beat even with "normal" self-contained C code.

I think it would be very cool if we can backport some if not the whole library to `cryptonite-openssl`, but the way I see it I would still like to keep `fastpbkdf-hs` around (instead of suppressing it and merging it with this library) merely because I'd love for the end user to be able to pick either the lean library or the more comprehensive toolkit (the cryptonite project).

Said that, the two alternatives I see are:

* Have an explicit dependency upon `fastpbkdf2-hs` and build the usual Cryptonite-like API on top of those low level functions

* Avoid using `fastpbkdf2` entirely and have Cryptonite use OpenSSL directly, but there will be a performance tax

You also mentioned on Twitter this:

> you can probably change the openssl call to cryptonite C libs and you can drop the openssl dependency and retain the speed.

I'm not sure this is necessarily true due to the fact OpenSSL uses some optimised Assembly (see above). Can you elaborate a bit more? Thank you!

Alfredo

**Comment by vincenthz** [comment]
That's fine if you want to keep`fastpbkdf2` going, up to you really. you could move it under the haskell-crypto organisation umbrella too if you want too. Related to adding the features in cryptonite-openssl, obviously the "simple thing" is to just add it as is, depending on openssl function , and export a pbkdf2 module.

But I think that would have more values to be able to get rid of the openssl dependency (specially on windows/osx), and it would be certainly interesting to see what kind of performance difference we have. OpenSSL is not so different from cryptonite's hashes function in term of performance (or at least it uses to, I haven't benchmarked in a long time), I think most of the difference are due to have to jump between haskell and C all the time in cryptonite right now, not to individual hashes performance.

**Comment by adinapoli** [comment]
Hey Vincent!

> OpenSSL is not so different from cryptonite's hashes function in term of performance (or at least it uses to, I haven't benchmarked in a long time), I think most of the difference are due to have to jump between haskell and C all the time in cryptonite right now, not to individual hashes performance.

I would be very interested as well, although it could take a bit of time to get ported over. Maybe the short term plan could be to do the "simple thing" as you described and the long term could be porting. Provided the Haskell API remains stable, we shouldn't have problems of sort in changing the underlying C layer.
